export type RosterSeedRow = {
  payrollGroup: "CONFI" | "R&F";
  fullName: string;
  company: string;
  department: string;
};

/** Transcribed from the provided employee roster spreadsheet. */
export const ROSTER_SEED_DATA: RosterSeedRow[] = [
  { payrollGroup: "CONFI", fullName: "ALMADOR, DARILYN ANDAMON", company: "DSRDC", department: "Admin" },
  { payrollGroup: "CONFI", fullName: "DUMAUM, CEASAR IAN RANESIS", company: "DSRDC", department: "Admin" },
  { payrollGroup: "CONFI", fullName: "LORENO, KAREN JOY SUSAN", company: "DSRDC", department: "Admin" },
  { payrollGroup: "CONFI", fullName: "OLEA, ANNA MARIA TITO", company: "DSRDC", department: "Admin" },
  { payrollGroup: "CONFI", fullName: "YRAY, JOHN IRENE DEL CAMPO", company: "DSRDC", department: "Admin" },
  { payrollGroup: "CONFI", fullName: "OLIVAR, ROBINSON JUNTILLA", company: "DSRDC", department: "Business Development" },
  { payrollGroup: "CONFI", fullName: "DEL ROSARIO, PHILLIP REY AMOSUIS", company: "DSRDC", department: "Engineering" },
  { payrollGroup: "CONFI", fullName: "GODMALIN, KENT BERNARD MEDINA", company: "DSRDC", department: "Engineering" },
  { payrollGroup: "CONFI", fullName: "PEDROSO, RUFA AMPER", company: "DSRDC", department: "Engineering" },
  { payrollGroup: "CONFI", fullName: "PONCE, KENT NINO", company: "DSRDC", department: "Marketing" },
  { payrollGroup: "CONFI", fullName: "DEL CAMPO, JOSEPH PAHAMOTANG", company: "DSRDC", department: "Motorpool" },
  { payrollGroup: "CONFI", fullName: "SO 2, DENVER TE", company: "DSRDC", department: "Officers" },
  { payrollGroup: "CONFI", fullName: "SALON, ROYNE LANZADERAS", company: "DSRDC", department: "Operations" },
  { payrollGroup: "CONFI", fullName: "CAMARILLO, JAY LORD ESPINA", company: "DIC - BEERZONE", department: "Admin" },
  { payrollGroup: "CONFI", fullName: "YULO, RONALD MANLOZA", company: "DIC - BEERZONE", department: "Admin" },
  { payrollGroup: "CONFI", fullName: "LIVA, ANDREW IBANEZ", company: "DIC - BEERZONE", department: "Production" },
  { payrollGroup: "CONFI", fullName: "LUMAYA, ARTHUR GUMABAO", company: "DIC - BEERZONE", department: "Production" },
  { payrollGroup: "CONFI", fullName: "MAGBANUA, MATHEW SAMILLANO", company: "DIC - BEERZONE", department: "Service" },
  { payrollGroup: "CONFI", fullName: "RAMIREZ, JESAR DAGPIN", company: "DIC - BEERZONE", department: "Service" },
  { payrollGroup: "CONFI", fullName: "ABALLE, RUBELYN BONTOG", company: "MTEI", department: "Accounting" },
  { payrollGroup: "CONFI", fullName: "BULE, BELINDA HAIN", company: "MTEI", department: "Accounting" },
  { payrollGroup: "CONFI", fullName: "DUGA, JAKELYN HINOSA", company: "MTEI", department: "Accounting" },
  { payrollGroup: "CONFI", fullName: "MAGNO, MONDRAD JOSEPH QUIRING", company: "MTEI", department: "Accounting" },
  { payrollGroup: "CONFI", fullName: "SALON, MYRALEN QUITONG", company: "MTEI", department: "Accounting" },
  { payrollGroup: "CONFI", fullName: "BADE, GWENDOLIN ABABA", company: "MTEI", department: "Finance" },
  { payrollGroup: "CONFI", fullName: "COLE, AIREEN MONTELIZA", company: "MTEI", department: "Finance" },
  { payrollGroup: "CONFI", fullName: "GALVEZ, JUDELYN DORDAS", company: "MTEI", department: "Finance" },
  { payrollGroup: "CONFI", fullName: "CENTO, ANJEANETH LAMERA", company: "MTEI", department: "Human Resource" },
  { payrollGroup: "CONFI", fullName: "DECIERDO, RAMIL TORREGOSA", company: "MTEI", department: "IT" },
  { payrollGroup: "CONFI", fullName: "LORENO, JAYSON ALFONSO", company: "MTEI", department: "IT" },
  { payrollGroup: "CONFI", fullName: "TE, RHANDOLF BAGUIO", company: "MTEI", department: "IT" },
  { payrollGroup: "CONFI", fullName: "BAGASBAS, BRUCE PETER MENAC", company: "MTEI", department: "Operations" },
  { payrollGroup: "CONFI", fullName: "BORONGAN, KAREN ACAS", company: "MTEI", department: "Operations" },
  { payrollGroup: "CONFI", fullName: "FERNANDEZ, MYRTEL ROSE PLOYA", company: "MTEI", department: "Sales" },
  { payrollGroup: "CONFI", fullName: "OCHIA, ANALUZ DECCAMPO", company: "MTEI", department: "Sales" },
  { payrollGroup: "CONFI", fullName: "SINGCO, RIZZA MAE MANHANO", company: "MTEI", department: "Sales" },
  { payrollGroup: "R&F", fullName: "DALISAY, JO ANN SABORDO", company: "MTEI", department: "Accounting" },
  { payrollGroup: "R&F", fullName: "DALISAY, JOHN PAUL CORBES", company: "MTEI", department: "Accounting" },
  { payrollGroup: "R&F", fullName: "DELGADO, JELIECA URBANO", company: "MTEI", department: "Accounting" },
  { payrollGroup: "R&F", fullName: "LIANZO, RODEL ENOC", company: "MTEI", department: "Accounting" },
  { payrollGroup: "R&F", fullName: "QUIÑO, KATRINA TANQUILAN", company: "MTEI", department: "Accounting" },
  { payrollGroup: "R&F", fullName: "SOLDIA, PHILIP CURT ESPAÑOLA", company: "MTEI", department: "Accounting" },
  { payrollGroup: "R&F", fullName: "PADILLA, SALVADOR BORCELS", company: "MTEI", department: "Finance" },
  { payrollGroup: "R&F", fullName: "QUIAP, ROSAURO ROXAS", company: "MTEI", department: "Finance" },
  { payrollGroup: "R&F", fullName: "PACALDO, VIRGIE LYN MACARANAS", company: "MTEI", department: "Human Resource" },
  { payrollGroup: "R&F", fullName: "CABATUAN, BRYAN ILIW-ILIW", company: "MTEI", department: "Importation" },
  { payrollGroup: "R&F", fullName: "MONTEFALCON, MA. LUISA CALBOS", company: "MTEI", department: "Importation" },
  { payrollGroup: "R&F", fullName: "GUABLAS, MICHAEL RYAN SERASPE", company: "MTEI", department: "IT" },
  { payrollGroup: "R&F", fullName: "SAGAL, RODULF DE LOS REYES", company: "MTEI", department: "IT" },
  { payrollGroup: "R&F", fullName: "ALINABON, CATALINA BANGUIS", company: "MTEI", department: "Operations" },
  { payrollGroup: "R&F", fullName: "AMBID JR., ALFREDO GUADALQUINGA", company: "MTEI", department: "Operations" },
  { payrollGroup: "R&F", fullName: "BALURA, EDGAR PALAÑA", company: "MTEI", department: "Operations" },
  { payrollGroup: "R&F", fullName: "BINASBAS, JONATHAN CARCALLAS", company: "MTEI", department: "Operations" },
  { payrollGroup: "R&F", fullName: "CASTRO, FIDEL VASQUEZ", company: "MTEI", department: "Operations" },
  { payrollGroup: "R&F", fullName: "DAGAMI, DANTE CABILAO", company: "MTEI", department: "Operations" },
  { payrollGroup: "R&F", fullName: "DE GRACIA, JOEL EDAR", company: "MTEI", department: "Operations" },
  { payrollGroup: "R&F", fullName: "DUNGOG, ROMEO SR. BELECARIO", company: "MTEI", department: "Operations" },
  { payrollGroup: "R&F", fullName: "EGARGUN, HILBERT DAGANATO", company: "MTEI", department: "Operations" },
  { payrollGroup: "R&F", fullName: "FERNANDEZ, BERLOMAR CHAVEZ", company: "MTEI", department: "Operations" },
  { payrollGroup: "R&F", fullName: "FORMON, JESSICA PAULLYN BASILO", company: "MTEI", department: "Operations" },
  { payrollGroup: "R&F", fullName: "FRONDOZA, REY ANDRES", company: "MTEI", department: "Operations" },
  { payrollGroup: "R&F", fullName: "GALDIANO, BENGIE ESTREMOS", company: "MTEI", department: "Operations" },
  { payrollGroup: "R&F", fullName: "JOCOY, ABUNDIO JR SILAKAN", company: "MTEI", department: "Operations" },
  { payrollGroup: "R&F", fullName: "LAAB, JERALD REDUCTO", company: "MTEI", department: "Operations" },
  { payrollGroup: "R&F", fullName: "LADIO, REYNATO INTEG", company: "MTEI", department: "Operations" },
  { payrollGroup: "R&F", fullName: "LIANG, ALMAN BIC", company: "MTEI", department: "Operations" },
  { payrollGroup: "R&F", fullName: "MAKIPUTIN JR., JOHNNY ARICLA", company: "MTEI", department: "Operations" },
  { payrollGroup: "R&F", fullName: "MALAWE, VOCARIE ACOMPAÑADO", company: "MTEI", department: "Operations" },
  { payrollGroup: "R&F", fullName: "MANORIÑA, RAMIR CRUZ", company: "MTEI", department: "Operations" },
  { payrollGroup: "R&F", fullName: "MERLOW, JOLLIE SECRETARIA", company: "MTEI", department: "Operations" },
  { payrollGroup: "R&F", fullName: "MONTA, ARIEL DECANO", company: "MTEI", department: "Operations" },
  { payrollGroup: "R&F", fullName: "NACUA, JESON BILLE", company: "MTEI", department: "Operations" },
  { payrollGroup: "R&F", fullName: "PALOMARES, MABELLE CADIGAL", company: "MTEI", department: "Operations" },
  { payrollGroup: "R&F", fullName: "PEDROSO, MARLON SOLIS", company: "MTEI", department: "Operations" },
  { payrollGroup: "R&F", fullName: "QUIBO, MAREDIN LAD", company: "MTEI", department: "Operations" },
  { payrollGroup: "R&F", fullName: "SALAS, REYNANTE VISTAN", company: "MTEI", department: "Operations" },
  { payrollGroup: "R&F", fullName: "SALVADOR, MARK", company: "MTEI", department: "Operations" },
  { payrollGroup: "R&F", fullName: "SOLIS, RANILO OFQUIRIA", company: "MTEI", department: "Operations" },
  { payrollGroup: "R&F", fullName: "TROYO, KENN PAOLO SERATO", company: "MTEI", department: "Operations" },
  { payrollGroup: "R&F", fullName: "UNGAY, JESSA MAE TABAR", company: "MTEI", department: "Operations" },
  { payrollGroup: "R&F", fullName: "AMOGUIS, MARY ROSE LUNA", company: "MTEI", department: "Sales" },
  { payrollGroup: "R&F", fullName: "RAGANAN, VEA BRIONES", company: "MTEI", department: "Sales" },
  { payrollGroup: "R&F", fullName: "BALDONADO, BRIAN REX LUNSAN", company: "MTEI", department: "Sales" },
  { payrollGroup: "R&F", fullName: "MONSANTO, RONILYN ENTAG", company: "MTEI", department: "Sales" },
  { payrollGroup: "R&F", fullName: "ROBLEDO, JAYSON LUMAMBA", company: "MTEI", department: "Sales" },
  { payrollGroup: "R&F", fullName: "BULTAHAN, LUZ LUMISTA", company: "DSRDC", department: "Accounting" },
  { payrollGroup: "R&F", fullName: "VIDUYA, EDERLIN ABITO", company: "DSRDC", department: "Accounting" },
  { payrollGroup: "R&F", fullName: "CABANDI, JEAN MUTIA", company: "DSRDC", department: "Admin" },
  { payrollGroup: "R&F", fullName: "DEGORIO, TEODELYN DEDAL", company: "DSRDC", department: "Admin" },
  { payrollGroup: "R&F", fullName: "DENSING, FLONIE MINGO", company: "DSRDC", department: "Admin" },
  { payrollGroup: "R&F", fullName: "KILAT, EDNA BENDIJO", company: "DSRDC", department: "Admin" },
  { payrollGroup: "R&F", fullName: "PAGADOR, ABRAHAM JR TALINES", company: "DSRDC", department: "Admin" },
  { payrollGroup: "R&F", fullName: "ALPUERTO, MICHAEL CANADA", company: "DSRDC", department: "Engineering" },
  { payrollGroup: "R&F", fullName: "CASANAAN, JAY NALAZA", company: "DSRDC", department: "Engineering" },
  { payrollGroup: "R&F", fullName: "CEPEDA, JESON MABONG", company: "DSRDC", department: "Engineering" },
  { payrollGroup: "R&F", fullName: "DE GUZMAN, JHONNA MARISSE AVISTAD", company: "DSRDC", department: "Engineering" },
  { payrollGroup: "R&F", fullName: "ESNARDO, JUSTIN SULTAN", company: "DSRDC", department: "Engineering" },
  { payrollGroup: "R&F", fullName: "FERNANDEZ, JAY MARC CASANILLO", company: "DSRDC", department: "Engineering" },
  { payrollGroup: "R&F", fullName: "FERNANDEZ, MICHAEL CHAGAS", company: "DSRDC", department: "Engineering" },
  { payrollGroup: "R&F", fullName: "KILAT, GLENN MARK BENDIJO", company: "DSRDC", department: "Engineering" },
  { payrollGroup: "R&F", fullName: "LAP LAP, JOHN GABRIEL RAMOSA", company: "DSRDC", department: "Engineering" },
  { payrollGroup: "R&F", fullName: "LUMAGASON, JOVAN ANGGOT", company: "DSRDC", department: "Engineering" },
  { payrollGroup: "R&F", fullName: "LUMANTAS JR, GIL MACANA", company: "DSRDC", department: "Engineering" },
  { payrollGroup: "R&F", fullName: "MEDEL, DENIS JOHN FERNANDEZ", company: "DSRDC", department: "Engineering" },
  { payrollGroup: "R&F", fullName: "OLARTE, JULIUS SARMIENTO", company: "DSRDC", department: "Engineering" },
  { payrollGroup: "R&F", fullName: "PADAYHAG, PHILIP DELA CRUZ", company: "DSRDC", department: "Engineering" },
  { payrollGroup: "R&F", fullName: "SARNE, ERNESTO JR. DAVID", company: "DSRDC", department: "Engineering" },
  { payrollGroup: "R&F", fullName: "TUMACA, NELSON TAMISIN", company: "DSRDC", department: "Engineering" },
  { payrollGroup: "R&F", fullName: "MOMO, DARYLL JEAN", company: "DSRDC", department: "Marketing" },
  { payrollGroup: "R&F", fullName: "DE LA CRUZ, MA. ELENA PARREÑO", company: "DSRDC", department: "Norfolk" },
  { payrollGroup: "R&F", fullName: "LASDOCE, SHEIN GONZAGA", company: "DSRDC", department: "Norfolk" },
  { payrollGroup: "R&F", fullName: "BULAWAN, KATLYN JOY PALMA", company: "DSRDC", department: "Property Management" },
  { payrollGroup: "R&F", fullName: "GACIS, JOMAR SANTOYA", company: "DSRDC", department: "Property Management" },
  { payrollGroup: "R&F", fullName: "SULAMAN, ROSLIE PIEDRAVERDE", company: "DSRDC", department: "Property Management" },
  { payrollGroup: "R&F", fullName: "DEMAR, LEO HOMECILLO", company: "DIC - Eskina", department: "Production" },
  { payrollGroup: "R&F", fullName: "EME, JUNREY", company: "DIC - Eskina", department: "Production" },
  { payrollGroup: "R&F", fullName: "HERNANDEZ, RUSSELL BARING", company: "DIC - Eskina", department: "Production" },
  { payrollGroup: "R&F", fullName: "MAGBANUA, JOANNA VIVIEN TANGUB", company: "DIC - Eskina", department: "Production" },
  { payrollGroup: "R&F", fullName: "MORANO, MELVIN GOMEZ", company: "DIC - Eskina", department: "Production" },
  { payrollGroup: "R&F", fullName: "YAGONG, CHRISTIAN DOMINIQUE CATAM", company: "DIC - Eskina", department: "Production" },
  { payrollGroup: "R&F", fullName: "BALABIS, REY ANGELO CAMACHO", company: "DIC - Eskina", department: "Service" },
  { payrollGroup: "R&F", fullName: "DEL CORRO, JEFFREY BUCTUAN", company: "DIC - Eskina", department: "Service" },
  { payrollGroup: "R&F", fullName: "DELA PEÑA, JOSEPH PAULISBO", company: "DIC - Eskina", department: "Service" },
  { payrollGroup: "R&F", fullName: "GARCIA, CHRISTIAN DAVE SULLA", company: "DIC - Eskina", department: "Service" },
  { payrollGroup: "R&F", fullName: "LIBA, DECO MIGUEL SINOGBUHAN", company: "DIC - Eskina", department: "Service" },
  { payrollGroup: "R&F", fullName: "PASAOL, IZZY BABE GEVERO", company: "DIC - Eskina", department: "Service" },
  { payrollGroup: "R&F", fullName: "PRADO, JAMES MARK RACURO", company: "DIC - Eskina", department: "Service" },
  { payrollGroup: "R&F", fullName: "RAMOS, JOEL GIGANTE", company: "DIC - Eskina", department: "Service" },
];
